baseURL = 'https://github.com/hifly81/hifly81.github.io'
languageCode = 'en-us'
title = "Giovanni Marigi's page"
theme = 'hugo-PaperMod'

[params]
author = "Giovanni Marigi"

  [params.shareButtons]
  networks = [ "linkedin", "twitter", "reddit" ]
  size = "small"
  icon = "solid"
  buttonMargin = "0.2em"
